// <auto-generated>
//   Generated by _gen_strings.py from the single key table. Do not edit by hand;
//   regenerate to keep Strings.resx / Strings.ko.resx / this file in sync.
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace ShotLog.Resources;

/// <summary>Typed accessor over the embedded Strings resources (neutral = English, ko satellite).</summary>
public static class Strings
{
    private static readonly ResourceManager _rm =
        new ResourceManager("ShotLog.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Overrides the lookup culture. Null falls back to CurrentUICulture.</summary>
    public static CultureInfo? Culture { get; set; }

    private static string G(string key) => _rm.GetString(key, Culture) ?? key;

    public static string Common_Save => G("Common_Save");
    public static string Common_Close => G("Common_Close");
    public static string Common_Delete => G("Common_Delete");
    public static string Common_Browse => G("Common_Browse");
    public static string Common_All => G("Common_All");
    public static string Common_Tags => G("Common_Tags");
    public static string Common_Preset => G("Common_Preset");
    public static string Common_DefaultPreset => G("Common_DefaultPreset");
    public static string Common_OK => G("Common_OK");
    public static string Common_Cancel => G("Common_Cancel");
    public static string Common_Done => G("Common_Done");
    public static string Common_Copy => G("Common_Copy");
    public static string Tray_CaptureMonitor => G("Tray_CaptureMonitor");
    public static string Tray_CaptureNote => G("Tray_CaptureNote");
    public static string Tray_CaptureRegion => G("Tray_CaptureRegion");
    public static string Tray_CaptureWindow => G("Tray_CaptureWindow");
    public static string Tray_CaptureClipboard => G("Tray_CaptureClipboard");
    public static string Tray_Inbox => G("Tray_Inbox");
    public static string Tray_Compose => G("Tray_Compose");
    public static string Tray_Settings => G("Tray_Settings");
    public static string Tray_Exit => G("Tray_Exit");
    public static string QuickNote_Title => G("QuickNote_Title");
    public static string QuickNote_Header => G("QuickNote_Header");
    public static string QuickNote_SaveLocation => G("QuickNote_SaveLocation");
    public static string QuickNote_TagsWatermark => G("QuickNote_TagsWatermark");
    public static string QuickNote_Memo => G("QuickNote_Memo");
    public static string QuickNote_Hint => G("QuickNote_Hint");
    public static string QuickNote_Discard => G("QuickNote_Discard");
    public static string QuickNote_SaveFailed => G("QuickNote_SaveFailed");
    public static string QuickNote_Annotate => G("QuickNote_Annotate");
    public static string Region_Title => G("Region_Title");
    public static string Region_Hint => G("Region_Hint");
    public static string Compose_Title => G("Compose_Title");
    public static string Compose_GroupBy => G("Compose_GroupBy");
    public static string Compose_Period => G("Compose_Period");
    public static string Compose_TitleLabel => G("Compose_TitleLabel");
    public static string Compose_OutputFolder => G("Compose_OutputFolder");
    public static string Compose_Preview => G("Compose_Preview");
    public static string Compose_IncludeFrontMatter => G("Compose_IncludeFrontMatter");
    public static string Compose_CreateAndOpen => G("Compose_CreateAndOpen");
    public static string Compose_Today => G("Compose_Today");
    public static string Compose_Last7 => G("Compose_Last7");
    public static string Compose_CountFormat => G("Compose_CountFormat");
    public static string Compose_DefaultTitleFormat => G("Compose_DefaultTitleFormat");
    public static string Compose_NoTags => G("Compose_NoTags");
    public static string Compose_NoMemo => G("Compose_NoMemo");
    public static string Compose_SelectAtLeastOne => G("Compose_SelectAtLeastOne");
    public static string Compose_ExportFailed => G("Compose_ExportFailed");
    public static string Compose_GeneratedStatusFormat => G("Compose_GeneratedStatusFormat");
    public static string Compose_RenderedPreview => G("Compose_RenderedPreview");
    public static string Compose_WebViewMissing => G("Compose_WebViewMissing");
    public static string Compose_CopyMarkdown => G("Compose_CopyMarkdown");
    public static string Compose_ExportHtml => G("Compose_ExportHtml");
    public static string Compose_CopiedStatus => G("Compose_CopiedStatus");
    public static string Compose_HtmlGeneratedFormat => G("Compose_HtmlGeneratedFormat");
    public static string Compose_ImageWidth => G("Compose_ImageWidth");
    public static string Compose_SelectAll => G("Compose_SelectAll");
    public static string Compose_SelectNone => G("Compose_SelectNone");
    public static string Inbox_Title => G("Inbox_Title");
    public static string Inbox_Refresh => G("Inbox_Refresh");
    public static string Inbox_ComposeButton => G("Inbox_ComposeButton");
    public static string Inbox_NoImage => G("Inbox_NoImage");
    public static string Inbox_DeleteButton => G("Inbox_DeleteButton");
    public static string Inbox_Empty => G("Inbox_Empty");
    public static string Inbox_NoMatch => G("Inbox_NoMatch");
    public static string Inbox_DeleteConfirmFormat => G("Inbox_DeleteConfirmFormat");
    public static string Inbox_DeleteTitle => G("Inbox_DeleteTitle");
    public static string Inbox_Annotate => G("Inbox_Annotate");
    public static string Inbox_CopyButton => G("Inbox_CopyButton");
    public static string Inbox_OpenButton => G("Inbox_OpenButton");
    public static string Inbox_DeleteSelected => G("Inbox_DeleteSelected");
    public static string Inbox_DeleteSelectedConfirmFormat => G("Inbox_DeleteSelectedConfirmFormat");
    public static string Inbox_NoneSelected => G("Inbox_NoneSelected");
    public static string Inbox_MoveToPreset => G("Inbox_MoveToPreset");
    public static string Inbox_MoveTitle => G("Inbox_MoveTitle");
    public static string Inbox_MovePrompt => G("Inbox_MovePrompt");
    public static string Inbox_MoveReplaceTags => G("Inbox_MoveReplaceTags");
    public static string Inbox_MoveDoneFormat => G("Inbox_MoveDoneFormat");
    public static string Inbox_MoveNoPresets => G("Inbox_MoveNoPresets");
    public static string Inbox_TipCopy => G("Inbox_TipCopy");
    public static string Inbox_TipAnnotate => G("Inbox_TipAnnotate");
    public static string Inbox_TipFolder => G("Inbox_TipFolder");
    public static string Inbox_TipDelete => G("Inbox_TipDelete");
    public static string Inbox_EditTags => G("Inbox_EditTags");
    public static string Inbox_TagsWatermark => G("Inbox_TagsWatermark");
    public static string Settings_Title => G("Settings_Title");
    public static string Settings_PresetsSection => G("Settings_PresetsSection");
    public static string Settings_Name => G("Settings_Name");
    public static string Settings_Folder => G("Settings_Folder");
    public static string Settings_DefaultTags => G("Settings_DefaultTags");
    public static string Settings_Color => G("Settings_Color");
    public static string Settings_AddPreset => G("Settings_AddPreset");
    public static string Settings_HotkeysSection => G("Settings_HotkeysSection");
    public static string Settings_HkInstant => G("Settings_HkInstant");
    public static string Settings_HkNote => G("Settings_HkNote");
    public static string Settings_HkRegion => G("Settings_HkRegion");
    public static string Settings_HkWindow => G("Settings_HkWindow");
    public static string Settings_HkInbox => G("Settings_HkInbox");
    public static string Settings_HkClipboard => G("Settings_HkClipboard");
    public static string Settings_HotkeyHint => G("Settings_HotkeyHint");
    public static string Settings_ExportSection => G("Settings_ExportSection");
    public static string Settings_DefaultOutputFolder => G("Settings_DefaultOutputFolder");
    public static string Settings_Sidecar => G("Settings_Sidecar");
    public static string Settings_Notify => G("Settings_Notify");
    public static string Settings_GeneralSection => G("Settings_GeneralSection");
    public static string Settings_AutoStart => G("Settings_AutoStart");
    public static string Settings_Language => G("Settings_Language");
    public static string Settings_LangSystem => G("Settings_LangSystem");
    public static string Settings_HkShortInstant => G("Settings_HkShortInstant");
    public static string Settings_HkShortNote => G("Settings_HkShortNote");
    public static string Settings_HkShortRegion => G("Settings_HkShortRegion");
    public static string Settings_HkShortWindow => G("Settings_HkShortWindow");
    public static string Settings_HkShortInbox => G("Settings_HkShortInbox");
    public static string Settings_HkShortClipboard => G("Settings_HkShortClipboard");
    public static string Settings_InvalidHotkeyFormat => G("Settings_InvalidHotkeyFormat");
    public static string Settings_AutoStartLockedTip => G("Settings_AutoStartLockedTip");
    public static string Annot_Title => G("Annot_Title");
    public static string Annot_Select => G("Annot_Select");
    public static string Annot_Pen => G("Annot_Pen");
    public static string Annot_Highlighter => G("Annot_Highlighter");
    public static string Annot_Arrow => G("Annot_Arrow");
    public static string Annot_Rect => G("Annot_Rect");
    public static string Annot_Text => G("Annot_Text");
    public static string Annot_Undo => G("Annot_Undo");
    public static string Annot_Clear => G("Annot_Clear");
    public static string Annot_Color => G("Annot_Color");
    public static string Annot_Width => G("Annot_Width");
    public static string Annot_TextWatermark => G("Annot_TextWatermark");
    public static string Dialog_Title => G("Dialog_Title");
    public static string Picker_Custom => G("Picker_Custom");
    public static string Export_Untitled => G("Export_Untitled");
    public static string Sidecar_Time => G("Sidecar_Time");
    public static string Notify_SavedFormat => G("Notify_SavedFormat");
    public static string Notify_Clipboard => G("Notify_Clipboard");
}
